name: 'eks-deploy'
description: 'The kubectl command line program as a GitHub Action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cluster }}
    - ${{ inputs.region }}
    - ${{ inputs.role }}
    - ${{ inputs.command }}
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  cluster:
    description: 'eks cluster name'
    required: true
  region:
    description: 'eks region'
    required: true
  role:
    description: 'eks role'
    required: true
  command:
    description: 'kubectl command to run, without the kubectl, e.g. `get pods`'
    required: true
